line_length:
- 200 # warning
- 300 # error

function_body_length:
- 45 # warning
- 300 # error

disabled_rules:
- trailing_whitespace
- file_length

- force_cast
- identifier_name

excluded:
  - Carthage
  - Pods
